// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxdnMSTEaxFT4UAD-LvzhR95xvz05KYqE',
    appId: '1:279256223636:web:933224a53418dadfdfc981',
    messagingSenderId: '279256223636',
    projectId: 'telmed-5c20c',
    authDomain: 'telmed-5c20c.firebaseapp.com',
    storageBucket: 'telmed-5c20c.firebasestorage.app',
    measurementId: 'G-WWCMFS3WEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiftojD16JyzG_zvB3f1r0kTqB-SVnEcA',
    appId: '1:279256223636:android:5a24a81ca0e16bd0dfc981',
    messagingSenderId: '279256223636',
    projectId: 'telmed-5c20c',
    storageBucket: 'telmed-5c20c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfmLzCBmifKkxl8it82MvWLZcYRJUwykU',
    appId: '1:279256223636:ios:3f8ebf9d80176bc8dfc981',
    messagingSenderId: '279256223636',
    projectId: 'telmed-5c20c',
    storageBucket: 'telmed-5c20c.firebasestorage.app',
    iosBundleId: 'com.example.telmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfmLzCBmifKkxl8it82MvWLZcYRJUwykU',
    appId: '1:279256223636:ios:3f8ebf9d80176bc8dfc981',
    messagingSenderId: '279256223636',
    projectId: 'telmed-5c20c',
    storageBucket: 'telmed-5c20c.firebasestorage.app',
    iosBundleId: 'com.example.telmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxdnMSTEaxFT4UAD-LvzhR95xvz05KYqE',
    appId: '1:279256223636:web:6cf27d545e25799bdfc981',
    messagingSenderId: '279256223636',
    projectId: 'telmed-5c20c',
    authDomain: 'telmed-5c20c.firebaseapp.com',
    storageBucket: 'telmed-5c20c.firebasestorage.app',
    measurementId: 'G-R0PQY9MKDQ',
  );
}
